CREATE TABLE IF NOT EXISTS markets (
    timestamp TIMESTAMPTZ,
    ticker VARCHAR(255) NOT NULL,
    series_ticker VARCHAR(255),
    event_ticker VARCHAR(255),
    title TEXT,
    subtitle TEXT,
    open_time TIMESTAMP,
    close_time TIMESTAMP,
    expiration_time TIMESTAMP,
    status VARCHAR(255),
    yes_bid BIGINT,
    yes_ask BIGINT,
    no_bid BIGINT,
    no_ask BIGINT,
    last_price BIGINT,
    volume BIGINT,
    volume_24h BIGINT,
    result VARCHAR(255),
    can_close_early BOOLEAN,
    cap_count BIGINT,
    PRIMARY KEY (timestamp, ticker)
);