INSERT INTO markets (
    timestamp,
    ticker,
    series_ticker,
    event_ticker,
    title,
    subtitle,
    open_time,
    close_time,
    expiration_time,
    status,
    yes_bid,
    yes_ask,
    no_bid,
    no_ask,
    last_price,
    volume,
    volume_24h,
    result,
    can_close_early,
    cap_count
)
SELECT 
    timestamp,
    ticker,
    series_ticker,
    event_ticker,
    title,
    subtitle,
    open_time,
    close_time,
    expiration_time,
    status,
    yes_bid,
    yes_ask,
    no_bid,
    no_ask,
    last_price,
    volume,
    volume_24h,
    result,
    can_close_early,
    cap_count
FROM {stage_table}
ON CONFLICT (timestamp, ticker)
DO UPDATE SET
    series_ticker = EXCLUDED.series_ticker,
    event_ticker = EXCLUDED.event_ticker,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    open_time = EXCLUDED.open_time,
    close_time = EXCLUDED.close_time,
    expiration_time = EXCLUDED.expiration_time,
    status = EXCLUDED.status,
    yes_bid = EXCLUDED.yes_bid,
    yes_ask = EXCLUDED.yes_ask,
    no_bid = EXCLUDED.no_bid,
    no_ask = EXCLUDED.no_ask,
    last_price = EXCLUDED.last_price,
    volume = EXCLUDED.volume,
    volume_24h = EXCLUDED.volume_24h,
    result = EXCLUDED.result,
    can_close_early = EXCLUDED.can_close_early,
    cap_count = EXCLUDED.cap_count;